package com.redhat.alcada;

/**
 * This class was automatically generated by the data modeler tool.
 */

public enum Comite {
    
    COMITE_A, COMITE_B, COMITE_C, COMITE_X, COMITE_Y, COMITE_Z;
    
} 