package com.redhat.alcada;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Elemento implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Elemento() {
    }

}