package com.redhat.alcada;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Elemento implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String nome;
   private com.redhat.alcada.Pais pais;
   private com.redhat.alcada.ClassificacaoCliente classificacao;
   private double valorOperacao;
   private int vencimentoOperacao;

   public Elemento()
   {
   }

   public java.lang.String getNome()
   {
      return this.nome;
   }

   public void setNome(java.lang.String nome)
   {
      this.nome = nome;
   }

   public com.redhat.alcada.Pais getPais()
   {
      return this.pais;
   }

   public void setPais(com.redhat.alcada.Pais pais)
   {
      this.pais = pais;
   }

   public com.redhat.alcada.ClassificacaoCliente getClassificacao()
   {
      return this.classificacao;
   }

   public void setClassificacao(
         com.redhat.alcada.ClassificacaoCliente classificacao)
   {
      this.classificacao = classificacao;
   }

   public double getValorOperacao()
   {
      return this.valorOperacao;
   }

   public void setValorOperacao(double valorOperacao)
   {
      this.valorOperacao = valorOperacao;
   }

   public int getVencimentoOperacao()
   {
      return this.vencimentoOperacao;
   }

   public void setVencimentoOperacao(int vencimentoOperacao)
   {
      this.vencimentoOperacao = vencimentoOperacao;
   }

   public Elemento(java.lang.String nome, com.redhat.alcada.Pais pais,
         com.redhat.alcada.ClassificacaoCliente classificacao,
         double valorOperacao, int vencimentoOperacao)
   {
      this.nome = nome;
      this.pais = pais;
      this.classificacao = classificacao;
      this.valorOperacao = valorOperacao;
      this.vencimentoOperacao = vencimentoOperacao;
   }

}