package com.redhat.alcada;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Grupo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<com.redhat.alcada.Elemento> elementos;

   public Grupo()
   {
   }

   public java.util.List<com.redhat.alcada.Elemento> getElementos()
   {
      return this.elementos;
   }

   public void setElementos(
         java.util.List<com.redhat.alcada.Elemento> elementos)
   {
      this.elementos = elementos;
   }

   public Grupo(java.util.List<com.redhat.alcada.Elemento> elementos)
   {
      this.elementos = elementos;
   }

}