package com.redhat.alcada;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Pais implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Pais() {
    }

}